### ISSUE TITLE
Use only one level subdomain

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#15]
We are using the manual method of setting up certificates / TLS secrets because our installation is on a private cloud so issuing certificates by LetsEncrypt is not an option.

We have a CA-signed multi-domain certificate but it is only valid for a single level of subdomains of our EOEPCA domain. Therefore, domains like _ades.our-eoepca-domain_ are secure but _console.minio.our-eoepca-domain_ is not.

Before deploying e.g. minio, we are changing the minio console host to _console-minio.eoepca-sciencehub.esa.int_ manually. But this could be the default. 

It could be the same (i.e. single-level subdomains) for other components that have this issue e.g. workspaces.

**Comment by rconway** [comment]
In general this is a more convenient approach. We need to make sure that Workspaces do not rely upon the multi-depth subdomains.

@james-hinton We should update the guide for minio console as per above.

**Comment by james-hinton** [comment]
#22
