### ISSUE TITLE
Data Access - examples for testing functionality

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#19]
The [EOEPCA 2.0 Data Access component's deployment instruction](https://eoepca.readthedocs.io/projects/deploy/en/2.0-beta/building-blocks/data-access/#validation) says:

> 4. Test Data Access Functionality:
> Verify that the Data Access services are operational by performing test actions through the APIs.

There are no examples given how to test the Data Access services and what test actions should be performed. It would be desirable to have a Swagger UI or similar, maybe Jupyter Notebooks, as well as a description what must be done to test Data Access.

**Comment by j08lue** [comment]
Thanks for calling this out. 

We have Swagger docs for all the Data Access BB components here: https://eoepca.readthedocs.io/projects/data-access/en/latest/api/endpoint-specification/

We have a plan to add elementary validation actions to CI/CD pipelines and will update the deployment instructions once these have been identified

- https://github.com/EOEPCA/resource-discovery/issues/86

**Comment by j08lue** [comment]
There are also the demo notebooks here: https://github.com/EOEPCA/demo

The part we added for the new eoAPI and Stacture based endpoints can be found here: https://github.com/EOEPCA/demo/pull/13/files

**Comment by james-hinton** [comment]
Thanks all, I have improved the Data Access validation section using a few of these links and descriptions - 0e1caf89cbe1686a80fefdf9febcfd1f6373a572

Live at : https://eoepca.readthedocs.io/projects/deploy/en/2.0-beta/building-blocks/data-access/#testing-and-validation
