### ISSUE TITLE
Workspaces - workspace-api endpoint URL

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#26]
The URL in the documentation must be changed from:

> Workspace API: https://workspace-api-v2.${INGRESS_HOST}/

which sort of works but only outputs
`{"detail":"Not Found"}`

to:

> Workspace API: https://workspace-api-v2.${INGRESS_HOST}/docs

which is the correct URL for FastAPI

**Comment by james-hinton** [comment]
Fixed with 698069cb457f1d21e0867c79331def2a50736e3f
