### ISSUE TITLE
MLOps - check for OIDC provider

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#34]
It is understood that integration with OIDC is currently on the TODO list and there are no Keycloak component installation scripts yet. However, since a working OIDC provider is listed as a prerequisite for installing MLOps, the check-prerequisites script should check if an OIDC provider has been installed. It could do so by checking whether the OIDC_ISSUER_URL has been set, which should be set by the Keycloak (or any other OIDC provider) deployment.

**Comment by james-hinton** [comment]
Agreed, thanks for the suggestion.

Changes made in commit fa42c464b6d5766123ca4e7c81349f74b7505af9
