### ISSUE TITLE
MLOps - Gitlab installation

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#36]
The deployment of Gitlab from the settings generated by configure-mlosps.sh ends with the following message:

```
=== CRITICAL
The following charts are included for evaluation purposes only. They will not be supported by GitLab Support
for production workloads. Use Cloud Native Hybrid deployments for production. For more information visit
https://docs.gitlab.com/charts/installation/index.html#use-the-reference-architectures.
- PostgreSQL
- Redis
- Gitaly

=== NOTICE
The minimum required version of PostgreSQL is now 13. See https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/doc/installation/upgrade.md for more details.
Help us improve the installation experience, let us know how we did with a 1 minute survey:https://gitlab.fra1.qualtrics.com/jfe/form/SV_6kVqZANThUQ1bZb?installation=helm&release=17-1
```

_Critical_ sounds pretty serious and may suggest that something is very wrong. We realize that this comes from a helm chart you are not responsible for, yet the Deployment Guide should at least explain that the described method of installation is suitable for test and reference deployments perhaps, but for production instances the user should refer to the Gitlab documentation on deploying Gitlab on kubernetes.

**Comment by james-hinton** [comment]
A disclaimer for the GitLab component is now included in the guide, with a pointer to the official GitLab documentation 35bf7f5c8dd9e25071c65e6aa1cfee43219d347f
