### ISSUE TITLE
Error pulling images from Docker Hub

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#37]
It frequently happens during deployment that the limit of pull rate from Docker Hub is exceeded and images fail to download, e.g.:

`  Warning  Failed     17s (x2 over 35s)  kubelet            Failed to pull image "eoepca/sharinghub:0.3.0": failed to pull and unpack image "docker.io/eoepca/sharinghub:0.3.0": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/eoepca/sharinghub/manifests/sha256:45bae3b91aa10e31067fee7311f499a44d85c1d6adf5bf99259b2ddcca6c0a0d: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
`
Eventually, after some time they are pulled and deployed correctly but it creates quite a long delay sometimes.

This can be avoided by authenticating to Docker Hub which will increase the pull limit somewhat. The Deployment Guide should explain how to do it, possibly in the _Infrastructure Deployment_ section. Even then, it is not an ultimate solution and perhaps a private repository should be set up with images necessary to deploy EOEPCA and deployment scripts should be changed accordingly.

**Comment by rconway** [comment]
In fact this is the approach that we took during the eoepca phase 1, see here - https://github.com/EOEPCA/eoepca/blob/develop/kubernetes/README.md#rke-configuration - although maybe it didn't make its way into the Deployment Guide.

That said - it may be difficult to provide general instructions as the setup steps may be a function of the kubernetes distribution in use. We have an `eoepca` account with dockerhub for this purpose.

Nevertheless, we will at minimum describe the need to consider this and, if possible, some general instructions.

**Comment by spinto** [comment]
I think what we can do is just put into the "pre-requisites" page, in the "recommended" part, a line telling that given the number of containers from dockerhub involved in a release of EOEPCA, to overcome possible image pull limits, it is recommended to setup Dockehub credentials or use a dockerhub proxy registry in the cluster. Just one line, nothing more.

**Comment by james-hinton** [comment]
This is now highlighted in a **Recommended Additional Steps** section see c5645462129dae91bf7a1ea00e720dd95f8f6a92
