### ISSUE TITLE
IAM - kc-postgres secret created after deployment

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#46]
I understand that the section about IAM is currently work in progress. One little fix that could be applied is that the secret _kc-postgres_ currently is created after the component is deployed with _helm_ which leads to pods initially failing due to lack of said secret. The secret should be created before the actual deployment. I guess in the final version it will be nicely wrapped up in _check-prerequisites_ and _configure-iam_ scripts and there will be no need to create the secret with a separate command, I'm just sharing my observation from the current state.

**Comment by james-hinton** [comment]
This is now part of an `apply-secrets.sh` script in the IAM component [here](https://github.com/EOEPCA/deployment-guide/pull/55/files#diff-f9b4e511be91f1be92c5d9a9dec978918543a70c92e840913742cd2f5d23560cR33)
