### ISSUE TITLE
IAM - missing CRDs

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#47]
The command to deploy ingress fails with the following error:
```
$ kubectl -n iam apply -f keycloak/generated-ingress.yaml
certificate.cert-manager.io/auth-apx created
resource mapping not found for name: "keycloak" namespace: "" from "keycloak/generated-ingress.yaml": no matches for kind "ApisixRoute" in version "apisix.apache.org/v2"
ensure CRDs are installed first
resource mapping not found for name: "keycloak" namespace: "" from "keycloak/generated-ingress.yaml": no matches for kind "ApisixTls" in version "apisix.apache.org/v2"
ensure CRDs are installed first
```
Apparently, custom resources _ApisixRoute_ and _ApisixTls_ are missing and there are no instructions how to install them.
I tried adding the CRDs with the following commands:
```
$ kubectl apply -f https://raw.githubusercontent.com/apache/apisix-ingress-controller/refs/heads/master/samples/deploy/crd/v1/ApisixRoute.yaml
$ kubectl apply -f https://raw.githubusercontent.com/apache/apisix-ingress-controller/refs/heads/master/samples/deploy/crd/v1/ApisixTls.yaml
```

I am not sure if these are the correct yaml files but after that, I was able to deploy ingress for Keycloak. However, the endpoint https://auth-apx.$INGRESS_HOST (https://auth-apx.eoepca-sciencehub.esa.int in our case) still returns HTTP error 404 and is not available.

**Comment by james-hinton** [comment]
This is now fixed as part of PR #55 -- https://github.com/EOEPCA/deployment-guide/pull/55/files#diff-1aff5648f65c9b2e64e2c6ffa62b566bd807d0fbed4b801d09629f6be5bc314cR74
