### ISSUE TITLE
EOEPCA V1.4 DEFAULT_MAX_RAM env var format

### ISSUE THREAD

**Issue by jzvolensky** [EOEPCA/deployment-guide#5]
Launching a custom process on the new 1.4 release starts a job but fails due to a configuration in the environmental variable DEFAULT_MAX_RAM=8gi. I have attached an image from the rest client with the output.

Basically, the value 8gi is not properly interpreted.

![EOEPCA_error](https://github.com/EOEPCA/deployment-guide/assets/120667628/510b38b5-12e6-4a27-938b-a4d83f981972)

I have tracked it down as one of the ZOO project variables. using the following:

```zsh
for ns in $(kubectl get ns -o jsonpath="{.items[*].metadata.name}"); do
  for pod in $(kubectl get pods -n $ns -o jsonpath="{.items[*].metadata.name}"); do
    echo "Namespace: $ns, Pod: $pod"
    kubectl exec -n $ns $pod -- env | grep DEFAULT_MAX_RAM
```

which returns

```zsh
Namespace: ingress-nginx, Pod: ingress-nginx-controller-6cf75f64cd-ljf7g
Namespace: kube-system, Pod: coredns-78fcd69978-2s94k
command terminated with exit code 126
Namespace: kube-system, Pod: etcd-eoepca
command terminated with exit code 126
Namespace: kube-system, Pod: kube-apiserver-eoepca
command terminated with exit code 126
Namespace: kube-system, Pod: kube-controller-manager-eoepca
command terminated with exit code 126
Namespace: kube-system, Pod: kube-proxy-46fdd
Namespace: kube-system, Pod: kube-scheduler-eoepca
command terminated with exit code 126
Namespace: kube-system, Pod: storage-provisioner
command terminated with exit code 126
Namespace: rm, Pod: minio-0
Namespace: rm, Pod: minio-1
Namespace: zoo, Pod: zoo-project-dru-kubeproxy-f4b964c5d-b4pzl
Namespace: zoo, Pod: zoo-project-dru-postgresql-0
Namespace: zoo, Pod: zoo-project-dru-rabbitmq-0
Namespace: zoo, Pod: zoo-project-dru-zoofpm-5d66d66558-952s4
Defaulted container "zoofpm" out of: zoofpm, init-wait-for-dependencies-zoofpm (init)
DEFAULT_MAX_RAM=8Gi
Namespace: zoo, Pod: zoo-project-dru-zookernel-7cb69c9548-wcxnd
```

System information:
Ubuntu 22.04 VM
Deployment guide 1.4 Processing deployment
12gb ram
max cores 4

Let me know if you need further information. Have a good day!

**Comment by fabricebrito** [comment]
Yes, the stack trace is clear.

**Comment by jzvolensky** [comment]
Thank you for the quick response. 

I understand, however, I never set this value anywhere, I am not passing resource requirements in the CWL (is that necessary?) so I thought that it could be some preconfigured value that is wrong. 

I performed standard processing deployment procedure and all I did was uncomment the max ram, cpu, and storage size. 

The code being run is a hydrological model which as far as I know does not set this value either (I can confirm tomorrow). 

Thanks

**Comment by jzvolensky** [comment]
Oh yes sorry,

 In `deployment-guide/deploy/processing/processing-options` I uncommented these values:

```
# Minikube options
# Tune the resources afforded to minikube (assuming the `docker` driver)
export MINIKUBE_CPU_AMOUNT=max
export MINIKUBE_MEMORY_AMOUNT=12g
export MINIKUBE_DISK_AMOUNT=50g
```

Other than that I keep the 'stock' configuration and do not touch or configure anything else. This is the same methodology which I have always used.

**Comment by rconway** [comment]
Can you update your CWL with resource requirements - in particular for the Workspace - e.g. https://github.com/EOEPCA/deployment-guide/blob/main/deploy/samples/requests/processing/convert-url-app.cwl#L16

**Comment by jzvolensky** [comment]
Sure, I will let you know!

**Comment by jzvolensky** [comment]
Alright so I did try to run it again with resource requirements set. It does actually start now and creates the processing environment

I do run into more issues but I believe this is on our end regarding the outputs not being properly set up yet. This is still very much work in progress.

For reference here is the CWL I am using for now. It is part of a hydrological model setup we are trying to package:

https://gist.github.com/jzvolensky/646fea0acbf4a388e58c6bb7ad177838

So, if I understand correctly, if you do not specify resource requirements, it defaults to a value which is using wrong units, is that correct? 

I have also attached the current error. It is not really relevant to this issue, but it might be useful for you (or not haha).

Thanks!

![ades-issue-update](https://github.com/EOEPCA/deployment-guide/assets/120667628/af173577-227c-4689-9e2e-8378de34f54e)

**Comment by jzvolensky** [comment]
Alright thank you very much.

I forgot the validator existed, I will check the cwls with it. Thanks for the links!

**Comment by fabricebrito** [comment]
> Re. "So, if I understand correctly, if you do not specify resource requirements, it defaults to a value which is using wrong units, is that correct?"
> 
> * We need to investigate the extent of this
> 
> But you should use the App Package Validator tool...
> 
> * https://github.com/EOEPCA/app-package-validation
> * https://pypi.org/project/ogc-ap-validator/
> 
> ...which may advocate the specification of Resource Requirements, in accordance with the best practice.
> 
> @fabricebrito (or maybe @gfenoy) Can you advise on the extent to which resource requirements must be specified in the AP CWL, and the behaviour of the ades/zoo-dru in the case they are omitted

@rconway the BP says: https://docs.ogc.org/bp/20-089r1.html#toc32 and the CWL runner used explains why it's needed: https://github.com/Duke-GCB/calrissian?tab=readme-ov-file#scalability--resource-requirements

**Comment by rconway** [comment]
So the BP does not make the ResourceRequirements mandatory - but it seems that, if they are omitted, then zoo throws an error. Maybe there is something to fix here. Perhaps need to check the `DEFAULT_MAX_RAM` value `8Gi` that is referenced in the original post.

**Comment by rconway** [comment]
OK. I think I found the root of the problem - in the Deployment Guide default values - https://github.com/EOEPCA/deployment-guide/blob/main/deploy/eoepca/eoepca-options#L78...

```
export PROCESSING_MAX_RAM="${PROCESSING_MAX_RAM:-8Gi}"
```

**Comment by jzvolensky** [comment]
Hi, yes that seems to be it. Thank you for the fix!

**Comment by rconway** [comment]
Closing, having diagnosed a problem with the defaults in the deployment guide.
This is now fixed here...
https://github.com/EOEPCA/deployment-guide/blob/6b9bb4567a81d82a6528d57d1ee72df9d2380000/deploy/eoepca/eoepca-options#L78
