### ISSUE TITLE
Processing - sample process deployment content type

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#50]
In the Deployment Guide the command to deploy a process in ZOO is:
```
curl -X POST "https://zoo.<INGRESS_HOST>/ogc-api/processes" \
-H "Content-Type: application/json" \
-d '{
  "executionUnit": {
    "href": "https://raw.githubusercontent.com/EOEPCA/deployment-guide/2.0-beta/scripts/processing/oapip/examples/water-bodies.cwl",
    "type": "application/cwl"
  }
}'
```

The Content-Type here is _application/json_ while in the ZOO's Swagger UI it is _application/ogcapppkg+json_. They do seem to produce the same result i.e. the process is correctly deployed (also using the latter in the command line) but this could be confusing to the user.

**Comment by james-hinton** [comment]
Updated in e923faf3ac98d641b427760fa4c775eda9b7cf23
